# Generated by Django 5.0.2 on 2024-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typing_speed',
            field=models.IntegerField(default=0),
        ),
    ]
